### ISSUE TITLE
Blank Screen in Admin CP

### ISSUE THREAD

**Issue by thecloud-guy** [PirataNervo/newpoints#6]
When I click the NewPoints link in the Admin CP, I get a blank screen. Tried removing and adding the plugin again but not getting anywhere.

**Comment by PirataNervo** [comment]
Please check your Apache error logs. Let me know what they say.

**Comment by thecloud-guy** [comment]
Deleted the log and created it again, and tried the operation again, no errors though. If it helps I'm getting no HTML output either.

I did get it working though, I went from PHP 7.0.6 down to 5.6.21 and it seems to be working now.

**Comment by PirataNervo** [comment]
I have no idea then. A white page usually means there's something wrong (error/warning) and Apache stops the page from loading and produces an entry in the log. In this case, I really don't know what happened.

**Comment by thecloud-guy** [comment]
No worries, I got it working, thanks for taking the time to reply :)
